using Microsoft.CodeAnalysis;

namespace Soenneker.Gen.Razor.ImageOptimizer.Webp;

[Generator]
public sealed class ImageOptimizerWebpGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("Generated.g.cs", "// Generated by Soenneker.Gen.Razor.ImageOptimizer.Webp\n");
        });
    }
}
